version: '3.3'

services:
  web:
    build: .
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - .docker.env
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - oauth-mongodb-data:/data/db
volumes:
  oauth-mongodb-data:
